[workspace]
resolver = "3"
members = [
    "app/api",
    "app/node",
    "crates/assets",
    "crates/config",
    "crates/database",
    "crates/migration",
]
default-members = ["app/api", "app/node", "crates/assets"]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
argon2 = "0.5"
axum = { version = "0.8", features = ["multipart"] }
axum-reverse-proxy = "1.0"
async-trait = "0.1"
axum-extra = { version = "0.10", features = ["cookie"] }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
mime_guess = "2"
rand_core = { version = "0.6", features = ["getrandom"] }
rustls = { version = "0.23", features = ["ring"] }
rust-embed = { version = "8.11", features = ["interpolate-folder-path"] }
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "with-uuid", "with-chrono", "mock"] }
sea-orm-migration = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
tempfile = "3"
tokio = { version = "1", features = ["fs", "macros", "net", "process", "rt-multi-thread", "time"] }
toml = "0.9"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["serde", "v4"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }

grass-worker-api = { path = "app/api" }
grass-worker-node = { path = "app/node" }
grass-worker-assets = { path = "crates/assets" }
grass-worker-config = { path = "crates/config" }
grass-worker-database = { path = "crates/database" }
grass-worker-migration = { path = "crates/migration" }
