[package]
name = "grass-cache"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
moka.workspace = true
redis.workspace = true
serde.workspace = true
time.workspace = true
tokio.workspace = true
