[package]
name = "grass-worker-api"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
argon2.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-reverse-proxy.workspace = true
chrono.workspace = true
grass-worker-assets.workspace = true
grass-worker-config.workspace = true
grass-worker-database.workspace = true
grass-worker-migration.workspace = true
hex.workspace = true
mime_guess.workspace = true
rand_core.workspace = true
rustls.workspace = true
sea-orm.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
