[package]
name = "grass-worker-api"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
axum-reverse-proxy.workspace = true
grass-worker-assets.workspace = true
grass-worker-database.workspace = true
grass-worker-migration.workspace = true
mime_guess.workspace = true
rustls.workspace = true
serde.workspace = true
tokio.workspace = true

grass-worker-config.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
tower.workspace = true
