[package]
name = "grass-worker-node"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
tokio.workspace = true

grass-worker-config.workspace = true

[dev-dependencies]
serde_json.workspace = true
tower.workspace = true
