[package]
name = "grass-crypto"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
argon2.workspace = true
base64.workspace = true
ring.workspace = true
serde.workspace = true
thiserror.workspace = true
